# Configuration file for custom scenarios for `premise`

---

# existing datasets to regionalize
regionalize:
  datasets:
    # gravel
    - name: adr gravel
      reference product: gravel, crushed, from adr
      exists in original database: False
    - name: gravel production, crushed
      reference product: gravel, crushed
      exists in original database: True
    - name: gravel and sand quarry operation
      reference product: gravel, round
      exists in original database: True
    # sand
    - name: has sand
      reference product: sand, from has
      exists in original database: False
    - name: gravel and sand quarry operation
      reference product: sand
      exists in original database: True
    - name: sand quarry operation, extraction from river bed
      reference product: sand
      exists in original database: True
    # ADR
    - name: adr (0-1 mm)
      reference product: intermediate (0-1 mm)
      exists in original database: False
    - name: adr (1-4 mm)
      reference product: intermediate (1-4 mm)
      exists in original database: False
    - name: advanced dry recovery (adr)
      reference product: intermediate (0-16 mm)
      exists in original database: False
    # HAS
    - name: has (0-0.125 mm)
      reference product: intermediate (0-0.125 mm)
      exists in original database: False
    - name: heated air classification (has)
      reference product: intermediate (0-4 mm)
      exists in original database: False
    # HVO Diesel
    - name: crude oil pretreatment
      reference product: pretreated oil
      exists in original database: False
    - name: hvo diesel production (roque et al 2023)
      reference product: hvo diesel
      exists in original database: False
    # concrete
    - name: market for concrete, normal strength
      reference product: concrete, normal strength
      exists in original database: True
    - name: concrete, all types to generic market for concrete, normal strength
      reference product: concrete, normal strength
      exists in original database: True

production pathways:
  # Production of gravel
  # Gravel from ADR
  GRAVEL_ADR:
    production volume:
      variable: Production|Gravel|GRAVEL_ADR
    ecoinvent alias:
      exists in original database: False
      name: adr gravel
      reference product: gravel, crushed, from adr
      new dataset: True
  # Gravel from virgin sources
  GRAVEL_CRUSHED:
    production volume:
      variable: Production|Gravel|GRAVEL_CRUSHED
    ecoinvent alias:
      exists in original database: True
      name: gravel production, crushed
      reference product: gravel, crushed
  GRAVEL_ROUND:
    production volume:
      variable: Production|Gravel|GRAVEL_ROUND
    ecoinvent alias:
      exists in original database: True
      name: gravel and sand quarry operation
      reference product: gravel, round
  # Production of sand
  # Sand from HAS
  SAND_HAS:
    production volume:
      variable: Production|Sand|SAND_HAS
    ecoinvent alias:
      exists in original database: False
      name: has sand
      reference product: sand, from has
      new dataset: True
  # Sand from virgin sources
  SAND_QUARRY:
    production volume:
      variable: Production|Sand|SAND_QUARRY
    ecoinvent alias:
      exists in original database: True
      name: gravel and sand quarry operation
      reference product: sand
  SAND_RIVER:
    production volume:
      variable: Production|Sand|SAND_RIVER
    ecoinvent alias:
      exists in original database: True
      name: sand quarry operation, extraction from river bed
      reference product: sand
  SAND_PIT:
    production volume:
      variable: Production|Sand|SAND_PIT
    ecoinvent alias:
      exists in original database: True
      name: sand quarry operation, open pit mine
      reference product: sand
  SAND_ZINC:
    production volume:
      variable: Production|Sand|SAND_ZINC
    ecoinvent alias:
      exists in original database: True
      name: zinc mine operation
      reference product: sand

markets:
  # with recycled components
  # Gravel
  - name: market for gravel, crushed, incl recycled
    reference product: gravel, crushed
    unit: kilogram
    includes:
      - GRAVEL_ADR
      - GRAVEL_CRUSHED
    replaces:
      - name: market for gravel, crushed
        product: gravel, crushed
  - name: market for gravel, round, incl recycled
    reference product: gravel, round
    unit: kilogram
    includes:
      - GRAVEL_ADR
      - GRAVEL_ROUND
    replaces:
      - name: market for gravel, round
        product: gravel, round
  # Sand
  - name: market for sand, incl recycled
    reference product: sand
    unit: kilogram
    includes:
      - SAND_HAS
      - SAND_QUARRY
      - SAND_RIVER
      - SAND_PIT
      - SAND_ZINC
    replaces:
      - name: market for sand
        product: sand
  # without recycled components, these are only added to compare against the 'recycled' market
  # Gravel
  - name: market for gravel, crushed, COMPARE
    reference product: gravel, crushed, COMPARE
    unit: kilogram
    includes:
      - GRAVEL_CRUSHED
  - name: market for gravel, round, COMPARE
    reference product: gravel, round, COMPARE
    unit: kilogram
    includes:
      - GRAVEL_ROUND
  # Sand
  - name: market for sand, COMPARE
    reference product: sand, COMPARE
    unit: kilogram
    includes:
      - SAND_QUARRY
      - SAND_RIVER
      - SAND_PIT
      - SAND_ZINC
  # without recycled components, these are only added to compare against the 'recycled' market
  # Gravel
  - name: market for gravel, recycled, COMPARE
    reference product: gravel, recycled, COMPARE
    unit: kilogram
    includes:
      - GRAVEL_ADR
  # Sand
  - name: market for sand, recycled, COMPARE
    reference product: sand, recycled, COMPARE
    unit: kilogram
    includes:
      - SAND_HAS