# Configuration file for custom scenarios for `premise`

---

production pathways:
  # Production of gravel
  # Gravel from ADR
  GRAVEL_ADR:
    production volume:
      variable: Production|Gravel|GRAVEL_ADR
    ecoinvent alias:
      exists in original database: False
      name: ADR gravel
      reference product: gravel, crushed, from ADR
      regionalize: True
      new dataset: True
  # Gravel from virgin sources
  GRAVEL_CRUSHED:
    production volume:
      variable: Production|Gravel|GRAVEL_CRUSHED
    ecoinvent alias:
      exists in original database: True
      name: gravel production, crushed
      reference product: gravel, crushed
      regionalize: True
  GRAVEL_ROUND:
    production volume:
      variable: Production|Gravel|GRAVEL_ROUND
    ecoinvent alias:
      exists in original database: True
      name: gravel and sand quarry operation
      reference product: gravel, round
      regionalize: True
  # Production of sand
  # Sand from HAS
  SAND_HAS:
    production volume:
      variable: Production|Sand|SAND_HAS
    ecoinvent alias:
      exists in original database: False
      name: HAS sand
      reference product: sand, from HAS
      regionalize: True
      new dataset: True
  # Sand from virgin sources
  SAND_QUARRY:
    production volume:
      variable: Production|Sand|SAND_QUARRY
    ecoinvent alias:
      exists in original database: True
      name: gravel and sand quarry operation
      reference product: sand
      regionalize: True
  SAND_RIVER:
    production volume:
      variable: Production|Sand|SAND_RIVER
    ecoinvent alias:
      exists in original database: True
      name: sand quarry operation, extraction from river bed
      reference product: sand
      regionalize: True
  SAND_PIT:
    production volume:
      variable: Production|Sand|SAND_PIT
    ecoinvent alias:
      exists in original database: True
      name: sand quarry operation, open pit mine
      reference product: sand
  SAND_ZINC:
    production volume:
      variable: Production|Sand|SAND_ZINC
    ecoinvent alias:
      exists in original database: True
      name: zinc mine operation
      reference product: sand
  # Use 'Dummy' variables to regionalize processes
  # ADR
  INTERMEDIATE_ADR_0_1:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: ADR (0-1 mm)
      reference product: intermediate (0-1 mm)
      regionalize: True
      new dataset: True
  INTERMEDIATE_ADR_1_4:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: ADR (1-4 mm)
      reference product: intermediate (1-4 mm)
      regionalize: True
      new dataset: True
  INTERMEDIATE_ADR_0_16:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: advanced dry recovery (ADR)
      reference product: intermediate (0-16 mm)
      regionalize: True
      new dataset: True
  # HAS
  INTERMEDIATE_HAS_0_0125:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: HAS (0-0.125 mm)
      reference product: intermediate (0-0.125 mm)
      regionalize: True
      new dataset: True
  INTERMEDIATE_HAS_0_4:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: heated air classification (HAS)
      reference product: intermediate (0-4 mm)
      regionalize: True
      new dataset: True
  # HVO Diesel
  CRUDE_OIL_PRE:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: Crude oil Pretreatment
      reference product: pretreated oil
      regionalize: True
      new dataset: True
  HVO_DIESEL_PROD:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: HVO diesel production (Roque et al 2023)
      reference product: HVO diesel
      regionalize: True
      new dataset: True
  HVO_DIESEL_BURNED:
    production volume:
      variable: DUMMY
    ecoinvent alias:
      exists in original database: False
      name: HVO diesel, burned in building machine
      reference product: HVO diesel, burned in building machine
      regionalize: True
      new dataset: True

markets:
  # Gravel
  - name: market for gravel, crushed
    reference product: gravel, crushed
    unit: kilogram
    includes:
      - GRAVEL_ADR
      - GRAVEL_CRUSHED
    replaces:
      - name: market for gravel, crushed
        product: gravel, crushed
    except regions:
      - World
  - name: market for gravel, round
    reference product: gravel, round
    unit: kilogram
    includes:
      - GRAVEL_ADR
      - GRAVEL_ROUND
    replaces:
      - name: market for gravel, round
        product: gravel, round
    except regions:
      - World
  - name: market for sand
    reference product: sand
    unit: kilogram
    includes:
      - SAND_HAS
      - SAND_QUARRY
      - SAND_RIVER
      - SAND_PIT
      - SAND_ZINC
    replaces:
      - name: market for sand
        product: sand
    except regions:
      - World